export const skills = [
	{ name: "HTML" },
	{ name: "CSS" },
	{ name: "SASS/SCSS" },
	{ name: "BEM" },
	{ name: "JavaScript" },
	{ name: "TypeScript" },
	{ name: "Cross-browser & adaptive layout" },
	{ name: "React" },
	{ name: "Redux Toolkit" },
	{ name: "Mobx" },
	{ name: "Webpack" },
	{ name: "Vite" },
	{ name: "Git" },
	{ name: "React Hook Form" },
	{ name: "Formik" },
	{ name: "i18next" },
	{ name: "styled components" },
	{ name: "MUI" },
	{ name: "yup" },
	{ name: "Figma" },
	{ name: "Firebase" },
];
